### ISSUE TITLE
Addon does not load correctly on Linux

### ISSUE THREAD

**Issue by subacoustic** [awesmubarak/koboanki#5]
Addon does not load correctly on restart of Anki.  Here´s the error message.

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Koboanki v200':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 80, in loadAddons
    __import__(dir)
  File "/home/USERNAME/.local/share/Anki2/addons21/197599239/__init__.py", line 5, in <module>
    from aqt.utils import showInfo, qconnect, tr, getFile
ImportError: cannot import name 'qconnect' from 'aqt.utils' (/usr/share/anki/aqt/utils.py)

**Comment by awesmubarak** [comment]
Hmm I haven't been able to reproduce this issue myself. I've just published v2.0.1 where I fixed a couple of bugs, does the issue persist there too?

**Comment by subacoustic** [comment]
The same error unfortunately - it looks like you´re on a Mac whereas I´m on Linux... 

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Koboanki v201':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 80, in loadAddons
    __import__(dir)
  File "/home/USERNAME/.local/share/Anki2/addons21/197599239/__init__.py", line 5, in <module>
    from aqt.utils import showInfo, qconnect, tr, getFile
ImportError: cannot import name 'qconnect' from 'aqt.utils' (/usr/share/anki/aqt/utils.py)

**Comment by awesmubarak** [comment]
Thanks, I'll test it on linux for the next update!

**Comment by Kumirei** [comment]
It's working fine for me on Linux Mint 20.2 with
Cinnamon 5.0.7
Anki v.2.1.49
Python 3.8.1
Qt 5.15.1
PyQt 5.15.1

**Comment by subacoustic** [comment]
Thanks Kumirei, I had been using Anki from the default repositories, I updated to Anki v.2.1.49 and it now installs correctly however on import, most words failed to import - perhaps because they are in multiple languages(?)

**Comment by Kumirei** [comment]
The API that this addon uses halted support for languages other than English a few days ago, so at this moment only English works.
See https://github.com/meetDeveloper/freeDictionaryAPI/issues/102#issuecomment-1044295059

If you're using this for Japanese you could make it use Jisho for Japanese.

**Comment by subacoustic** [comment]
Thanks Kumirei, I'm mostly using the word save feature in the Kobo for French and Spanish... I guess I'll just keep adding words manually into Anki, cheers

**Comment by awesmubarak** [comment]
Apologies for the late response. You're right, unfortunately this is only working for english at the moment, and the number of words that can be added at once is also limited. I haven't abandoned the project at all, but need to make some time for it. I'm about 70% done with v3 which will solidify multi-language support, alongside a bunch of other features. Thanks for using it and raising issues anyway though!

**Comment by subacoustic** [comment]
v3 sounds great!  thanks for creating this!  The kobo / anki combination will be so great for learning other languages.  you rock!
